### ISSUE TITLE
overwriting a file crashes the tool

### ISSUE THREAD

**Issue by aphshir** [Overcop/Communicator#4]
While trying to overwrite a file the tool seems to throw an error:
`Traceback (most recent call last):
  File "main.py", line 29, in <module>
  File "communicator.py", line 191, in start
  File "communicator.py", line 26, in menu
  File "communicator.py", line 178, in prtclencrypt
TypeError: write() argument must be str, not bytes
[19876] Failed to execute script 'main' due to unhandled exception!`

this happens only with file encrypt as overwriting with a decrypted file works just fine.

**Comment by aphshir** [comment]
Sounds like a problem with the write type of the file.
